language: node_js

node_js:
  - '10'

branches:
  only:
    - master

cache:
  directories:
    - node_modules

script:
  - npm test

after_success:
  - codecov

before_install:
  - npm install -g codecov

sudo: false
